#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cassandra
Version  : 3.11.4
Release  : 7
URL      : https://github.com/apache/cassandra/archive/cassandra-3.11.4.tar.gz
Source0  : https://github.com/apache/cassandra/archive/cassandra-3.11.4.tar.gz
Source1  : cassandra.service
Source2  : cassandra.tmpfiles
Summary  : Cassandra is a highly scalable, eventually consistent, distributed, structured key-value store.
Group    : Development/Tools
License  : Apache-2.0
Requires: cassandra-config = %{version}-%{release}
Requires: cassandra-data = %{version}-%{release}
Requires: cassandra-services = %{version}-%{release}
Requires: openjdk
BuildRequires : Sphinx
BuildRequires : apache-ant
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-mvn
BuildRequires : mvn-ant
BuildRequires : mvn-ant-launcher
BuildRequires : mvn-antlr
BuildRequires : mvn-apache
BuildRequires : mvn-apache-rat
BuildRequires : mvn-asm
BuildRequires : mvn-byteman
BuildRequires : mvn-cassandra
BuildRequires : mvn-codehaus-jackson
BuildRequires : mvn-commons-beanutils
BuildRequires : mvn-commons-cli
BuildRequires : mvn-commons-codec
BuildRequires : mvn-commons-collections
BuildRequires : mvn-commons-compress
BuildRequires : mvn-commons-configuration
BuildRequires : mvn-commons-digester
BuildRequires : mvn-commons-el
BuildRequires : mvn-commons-httpclient
BuildRequires : mvn-commons-io
BuildRequires : mvn-commons-lang
BuildRequires : mvn-commons-math
BuildRequires : mvn-commons-math3
BuildRequires : mvn-commons-net
BuildRequires : mvn-commons-parent
BuildRequires : mvn-compile-command-annotations
BuildRequires : mvn-ecj
BuildRequires : mvn-ftpserver
BuildRequires : mvn-guava
BuildRequires : mvn-hadoop
BuildRequires : mvn-hsqldb
BuildRequires : mvn-jacoco
BuildRequires : mvn-jersey
BuildRequires : mvn-jets3t
BuildRequires : mvn-jetty
BuildRequires : mvn-jetty-parent
BuildRequires : mvn-jmh
BuildRequires : mvn-jna
BuildRequires : mvn-jopt-simple
BuildRequires : mvn-jsr305
BuildRequires : mvn-jsr311
BuildRequires : mvn-junit
BuildRequires : mvn-kosmosfs
BuildRequires : mvn-maven-ant-tasks
BuildRequires : mvn-metrics
BuildRequires : mvn-mina
BuildRequires : mvn-mvnplugins
BuildRequires : mvn-netty
BuildRequires : mvn-nicoulaj-parent
BuildRequires : mvn-ohc
BuildRequires : mvn-oro
BuildRequires : mvn-oss-parents
BuildRequires : mvn-ow2
BuildRequires : mvn-servlet-api
BuildRequires : mvn-slf4j
BuildRequires : mvn-stringtemplate4
BuildRequires : mvn-tomcat
BuildRequires : mvn-wikitext-project
BuildRequires : mvn-xmlenc
BuildRequires : openjdk
Patch1: 0001-Set-cassandra-runtime-directories-for-data-commitlog.patch
Patch2: 0002-remove-SNAPSHOT-from-the-version-string.patch

%description
Cassandra is a distributed (peer-to-peer) system for the management and storage of structured data.

%package config
Summary: config components for the cassandra package.
Group: Default

%description config
config components for the cassandra package.


%package data
Summary: data components for the cassandra package.
Group: Data

%description data
data components for the cassandra package.


%package services
Summary: services components for the cassandra package.
Group: Systemd services

%description services
services components for the cassandra package.


%prep
%setup -q -n cassandra-cassandra-3.11.4
%patch1 -p1
%patch2 -p1

%build
## build_prepend content
mkdir -p /builddir/.m2/
cp -r /usr/share/java/.m2/* /builddir/.m2/
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export ANT_HOME=/usr/share/ant
ant -d -v artifacts
%install

mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/cassandra.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/tmpfiles.d/cassandra.conf
## install_append content
mkdir -p %{buildroot}/usr/share/cassandra/
cp -r build/dist/* %{buildroot}/usr/share/cassandra/
chmod 0755 %{buildroot}/usr/share/cassandra/bin/*
rm -rf %{buildroot}/usr/share/cassandra/lib/sigar-bin/*.dll
rm -rf %{buildroot}/usr/share/cassandra/lib/sigar-bin/*.lib
rm -rf %{buildroot}/usr/share/cassandra/javadoc
## install_append end

%files
%defattr(-,root,root,-)

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/cassandra.conf

%files data
%defattr(-,root,root,-)
/usr/share/cassandra/CASSANDRA-14092.txt
/usr/share/cassandra/CHANGES.txt
/usr/share/cassandra/LICENSE.txt
/usr/share/cassandra/NEWS.txt
/usr/share/cassandra/NOTICE.txt
/usr/share/cassandra/bin/cassandra
/usr/share/cassandra/bin/cassandra.bat
/usr/share/cassandra/bin/cassandra.in.bat
/usr/share/cassandra/bin/cassandra.in.sh
/usr/share/cassandra/bin/cassandra.ps1
/usr/share/cassandra/bin/cqlsh
/usr/share/cassandra/bin/cqlsh.bat
/usr/share/cassandra/bin/cqlsh.py
/usr/share/cassandra/bin/debug-cql
/usr/share/cassandra/bin/debug-cql.bat
/usr/share/cassandra/bin/nodetool
/usr/share/cassandra/bin/nodetool.bat
/usr/share/cassandra/bin/source-conf.ps1
/usr/share/cassandra/bin/sstableloader
/usr/share/cassandra/bin/sstableloader.bat
/usr/share/cassandra/bin/sstablescrub
/usr/share/cassandra/bin/sstablescrub.bat
/usr/share/cassandra/bin/sstableupgrade
/usr/share/cassandra/bin/sstableupgrade.bat
/usr/share/cassandra/bin/sstableutil
/usr/share/cassandra/bin/sstableutil.bat
/usr/share/cassandra/bin/sstableverify
/usr/share/cassandra/bin/sstableverify.bat
/usr/share/cassandra/bin/stop-server
/usr/share/cassandra/bin/stop-server.bat
/usr/share/cassandra/bin/stop-server.ps1
/usr/share/cassandra/conf/README.txt
/usr/share/cassandra/conf/cassandra-env.ps1
/usr/share/cassandra/conf/cassandra-env.sh
/usr/share/cassandra/conf/cassandra-jaas.config
/usr/share/cassandra/conf/cassandra-rackdc.properties
/usr/share/cassandra/conf/cassandra-topology.properties
/usr/share/cassandra/conf/cassandra.yaml
/usr/share/cassandra/conf/commitlog_archiving.properties
/usr/share/cassandra/conf/cqlshrc.sample
/usr/share/cassandra/conf/hotspot_compiler
/usr/share/cassandra/conf/jvm.options
/usr/share/cassandra/conf/logback-tools.xml
/usr/share/cassandra/conf/logback.xml
/usr/share/cassandra/conf/metrics-reporter-config-sample.yaml
/usr/share/cassandra/conf/triggers/README.txt
/usr/share/cassandra/doc/SASI.md
/usr/share/cassandra/doc/cql3/CQL.css
/usr/share/cassandra/doc/cql3/CQL.html
/usr/share/cassandra/interface/cassandra.thrift
/usr/share/cassandra/lib/HdrHistogram-2.1.9.jar
/usr/share/cassandra/lib/ST4-4.0.8.jar
/usr/share/cassandra/lib/airline-0.6.jar
/usr/share/cassandra/lib/antlr-runtime-3.5.2.jar
/usr/share/cassandra/lib/apache-cassandra-3.11.4.jar
/usr/share/cassandra/lib/apache-cassandra-thrift-3.11.4.jar
/usr/share/cassandra/lib/asm-5.0.4.jar
/usr/share/cassandra/lib/caffeine-2.2.6.jar
/usr/share/cassandra/lib/cassandra-driver-core-3.0.1-shaded.jar
/usr/share/cassandra/lib/cassandra-driver-internal-only-3.10.zip
/usr/share/cassandra/lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip
/usr/share/cassandra/lib/commons-cli-1.1.jar
/usr/share/cassandra/lib/commons-codec-1.9.jar
/usr/share/cassandra/lib/commons-lang3-3.1.jar
/usr/share/cassandra/lib/commons-math3-3.2.jar
/usr/share/cassandra/lib/compress-lzf-0.8.4.jar
/usr/share/cassandra/lib/concurrent-trees-2.4.0.jar
/usr/share/cassandra/lib/concurrentlinkedhashmap-lru-1.4.jar
/usr/share/cassandra/lib/disruptor-3.0.1.jar
/usr/share/cassandra/lib/ecj-4.4.2.jar
/usr/share/cassandra/lib/futures-2.1.6-py2.py3-none-any.zip
/usr/share/cassandra/lib/guava-18.0.jar
/usr/share/cassandra/lib/high-scale-lib-1.0.6.jar
/usr/share/cassandra/lib/hppc-0.5.4.jar
/usr/share/cassandra/lib/jackson-core-asl-1.9.13.jar
/usr/share/cassandra/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/cassandra/lib/jamm-0.3.0.jar
/usr/share/cassandra/lib/javax.inject.jar
/usr/share/cassandra/lib/jbcrypt-0.3m.jar
/usr/share/cassandra/lib/jcl-over-slf4j-1.7.7.jar
/usr/share/cassandra/lib/jctools-core-1.2.1.jar
/usr/share/cassandra/lib/jflex-1.6.0.jar
/usr/share/cassandra/lib/jna-4.2.2.jar
/usr/share/cassandra/lib/joda-time-2.4.jar
/usr/share/cassandra/lib/json-simple-1.1.jar
/usr/share/cassandra/lib/jstackjunit-0.0.1.jar
/usr/share/cassandra/lib/libthrift-0.9.2.jar
/usr/share/cassandra/lib/licenses/ST4-4.0.8.txt
/usr/share/cassandra/lib/licenses/airline-0.6.txt
/usr/share/cassandra/lib/licenses/antlr-runtime-3.5.2.txt
/usr/share/cassandra/lib/licenses/asm-5.0.4.txt
/usr/share/cassandra/lib/licenses/caffeine-2.2.6.txt
/usr/share/cassandra/lib/licenses/cassandra-driver-3.0.1.txt
/usr/share/cassandra/lib/licenses/commons-cli-1.1.txt
/usr/share/cassandra/lib/licenses/commons-codec-1.9.txt
/usr/share/cassandra/lib/licenses/commons-lang3-3.1.txt
/usr/share/cassandra/lib/licenses/commons-math3-3.2.txt
/usr/share/cassandra/lib/licenses/compress-lzf-0.8.4.txt
/usr/share/cassandra/lib/licenses/concurrent-trees-2.4.0.txt
/usr/share/cassandra/lib/licenses/concurrentlinkedhashmap-lru-1.4.txt
/usr/share/cassandra/lib/licenses/disruptor-3.0.1.txt
/usr/share/cassandra/lib/licenses/ecj-4.4.2.txt
/usr/share/cassandra/lib/licenses/futures-2.1.6.txt
/usr/share/cassandra/lib/licenses/guava-18.0.txt
/usr/share/cassandra/lib/licenses/hdrhistogram-2.1.9.txt
/usr/share/cassandra/lib/licenses/high-scale-lib-1.0.6.txt
/usr/share/cassandra/lib/licenses/hppc-0.5.4.txt
/usr/share/cassandra/lib/licenses/jackson-core-asl-1.9.13.txt
/usr/share/cassandra/lib/licenses/jackson-mapper-asl-1.9.13.txt
/usr/share/cassandra/lib/licenses/jamm-0.3.0.txt
/usr/share/cassandra/lib/licenses/javax.inject.txt
/usr/share/cassandra/lib/licenses/jbcrypt-0.3m.txt
/usr/share/cassandra/lib/licenses/jcl-over-slf4j-1.7.7.txt
/usr/share/cassandra/lib/licenses/jctools-core-1.2.1.txt
/usr/share/cassandra/lib/licenses/jflex-1.6.0.txt
/usr/share/cassandra/lib/licenses/jna-4.2.2.txt
/usr/share/cassandra/lib/licenses/joda-time-2.4.txt
/usr/share/cassandra/lib/licenses/json-simple-1.1.txt
/usr/share/cassandra/lib/licenses/jstackjunit-0.0.1.txt
/usr/share/cassandra/lib/licenses/libthrift-0.9.2.txt
/usr/share/cassandra/lib/licenses/log4j-over-slf4j-1.7.7.txt
/usr/share/cassandra/lib/licenses/logback-classic-1.1.3.txt
/usr/share/cassandra/lib/licenses/logback-core-1.1.3.txt
/usr/share/cassandra/lib/licenses/lz4-1.3.0.txt
/usr/share/cassandra/lib/licenses/metrics-core-3.1.5.txt
/usr/share/cassandra/lib/licenses/metrics-jvm-3.1.5.txt
/usr/share/cassandra/lib/licenses/metrics-logback-3.1.5.txt
/usr/share/cassandra/lib/licenses/netty-all-4.0.44.Final.txt
/usr/share/cassandra/lib/licenses/ohc-0.4.4.txt
/usr/share/cassandra/lib/licenses/reporter-config-base-3.0.3.txt
/usr/share/cassandra/lib/licenses/reporter-config3-3.0.3.txt
/usr/share/cassandra/lib/licenses/sigar-1.6.4.txt
/usr/share/cassandra/lib/licenses/six-1.7.3.txt
/usr/share/cassandra/lib/licenses/slf4j-api-1.7.7.txt
/usr/share/cassandra/lib/licenses/snakeyaml-1.11.txt
/usr/share/cassandra/lib/licenses/snappy-java-1.1.1.7.txt
/usr/share/cassandra/lib/licenses/snowball-stemmer-1.3.0.581.1.txt
/usr/share/cassandra/lib/licenses/stream-2.5.2.txt
/usr/share/cassandra/lib/licenses/thrift-server-0.3.7.txt
/usr/share/cassandra/lib/log4j-over-slf4j-1.7.7.jar
/usr/share/cassandra/lib/logback-classic-1.1.3.jar
/usr/share/cassandra/lib/logback-core-1.1.3.jar
/usr/share/cassandra/lib/lz4-1.3.0.jar
/usr/share/cassandra/lib/metrics-core-3.1.5.jar
/usr/share/cassandra/lib/metrics-jvm-3.1.5.jar
/usr/share/cassandra/lib/metrics-logback-3.1.5.jar
/usr/share/cassandra/lib/netty-all-4.0.44.Final.jar
/usr/share/cassandra/lib/ohc-core-0.4.4.jar
/usr/share/cassandra/lib/ohc-core-j8-0.4.4.jar
/usr/share/cassandra/lib/reporter-config-base-3.0.3.jar
/usr/share/cassandra/lib/reporter-config3-3.0.3.jar
/usr/share/cassandra/lib/sigar-1.6.4.jar
/usr/share/cassandra/lib/sigar-bin/libsigar-amd64-freebsd-6.so
/usr/share/cassandra/lib/sigar-bin/libsigar-amd64-linux.so
/usr/share/cassandra/lib/sigar-bin/libsigar-amd64-solaris.so
/usr/share/cassandra/lib/sigar-bin/libsigar-ia64-hpux-11.sl
/usr/share/cassandra/lib/sigar-bin/libsigar-ia64-linux.so
/usr/share/cassandra/lib/sigar-bin/libsigar-pa-hpux-11.sl
/usr/share/cassandra/lib/sigar-bin/libsigar-ppc-aix-5.so
/usr/share/cassandra/lib/sigar-bin/libsigar-ppc-linux.so
/usr/share/cassandra/lib/sigar-bin/libsigar-ppc64-aix-5.so
/usr/share/cassandra/lib/sigar-bin/libsigar-ppc64-linux.so
/usr/share/cassandra/lib/sigar-bin/libsigar-s390x-linux.so
/usr/share/cassandra/lib/sigar-bin/libsigar-sparc-solaris.so
/usr/share/cassandra/lib/sigar-bin/libsigar-sparc64-solaris.so
/usr/share/cassandra/lib/sigar-bin/libsigar-universal-macosx.dylib
/usr/share/cassandra/lib/sigar-bin/libsigar-universal64-macosx.dylib
/usr/share/cassandra/lib/sigar-bin/libsigar-x86-freebsd-5.so
/usr/share/cassandra/lib/sigar-bin/libsigar-x86-freebsd-6.so
/usr/share/cassandra/lib/sigar-bin/libsigar-x86-linux.so
/usr/share/cassandra/lib/sigar-bin/libsigar-x86-solaris.so
/usr/share/cassandra/lib/six-1.7.3-py2.py3-none-any.zip
/usr/share/cassandra/lib/slf4j-api-1.7.7.jar
/usr/share/cassandra/lib/snakeyaml-1.11.jar
/usr/share/cassandra/lib/snappy-java-1.1.1.7.jar
/usr/share/cassandra/lib/snowball-stemmer-1.3.0.581.1.jar
/usr/share/cassandra/lib/stream-2.5.2.jar
/usr/share/cassandra/lib/thrift-server-0.3.7.jar
/usr/share/cassandra/pylib/cassandra-cqlsh-tests.sh
/usr/share/cassandra/pylib/cqlshlib/__init__.py
/usr/share/cassandra/pylib/cqlshlib/copyutil.py
/usr/share/cassandra/pylib/cqlshlib/cql3handling.py
/usr/share/cassandra/pylib/cqlshlib/cqlhandling.py
/usr/share/cassandra/pylib/cqlshlib/cqlshhandling.py
/usr/share/cassandra/pylib/cqlshlib/displaying.py
/usr/share/cassandra/pylib/cqlshlib/formatting.py
/usr/share/cassandra/pylib/cqlshlib/helptopics.py
/usr/share/cassandra/pylib/cqlshlib/pylexotron.py
/usr/share/cassandra/pylib/cqlshlib/saferscanner.py
/usr/share/cassandra/pylib/cqlshlib/setup.cfg
/usr/share/cassandra/pylib/cqlshlib/sslhandling.py
/usr/share/cassandra/pylib/cqlshlib/test/__init__.py
/usr/share/cassandra/pylib/cqlshlib/test/ansi_colors.py
/usr/share/cassandra/pylib/cqlshlib/test/basecase.py
/usr/share/cassandra/pylib/cqlshlib/test/cassconnect.py
/usr/share/cassandra/pylib/cqlshlib/test/run_cqlsh.py
/usr/share/cassandra/pylib/cqlshlib/test/test_cql_parsing.py
/usr/share/cassandra/pylib/cqlshlib/test/test_cqlsh_commands.py
/usr/share/cassandra/pylib/cqlshlib/test/test_cqlsh_completion.py
/usr/share/cassandra/pylib/cqlshlib/test/test_cqlsh_invocation.py
/usr/share/cassandra/pylib/cqlshlib/test/test_cqlsh_output.py
/usr/share/cassandra/pylib/cqlshlib/test/test_cqlsh_parsing.py
/usr/share/cassandra/pylib/cqlshlib/test/test_keyspace_init.cql
/usr/share/cassandra/pylib/cqlshlib/test/winpty.py
/usr/share/cassandra/pylib/cqlshlib/tracing.py
/usr/share/cassandra/pylib/cqlshlib/util.py
/usr/share/cassandra/pylib/cqlshlib/wcwidth.py
/usr/share/cassandra/pylib/requirements.txt
/usr/share/cassandra/pylib/setup.py
/usr/share/cassandra/tools/bin/cassandra-stress
/usr/share/cassandra/tools/bin/cassandra-stress.bat
/usr/share/cassandra/tools/bin/cassandra-stressd
/usr/share/cassandra/tools/bin/cassandra.in.bat
/usr/share/cassandra/tools/bin/cassandra.in.sh
/usr/share/cassandra/tools/bin/compaction-stress
/usr/share/cassandra/tools/bin/sstabledump
/usr/share/cassandra/tools/bin/sstabledump.bat
/usr/share/cassandra/tools/bin/sstableexpiredblockers
/usr/share/cassandra/tools/bin/sstableexpiredblockers.bat
/usr/share/cassandra/tools/bin/sstablelevelreset
/usr/share/cassandra/tools/bin/sstablelevelreset.bat
/usr/share/cassandra/tools/bin/sstablemetadata
/usr/share/cassandra/tools/bin/sstablemetadata.bat
/usr/share/cassandra/tools/bin/sstableofflinerelevel
/usr/share/cassandra/tools/bin/sstableofflinerelevel.bat
/usr/share/cassandra/tools/bin/sstablerepairedset
/usr/share/cassandra/tools/bin/sstablerepairedset.bat
/usr/share/cassandra/tools/bin/sstablesplit
/usr/share/cassandra/tools/bin/sstablesplit.bat
/usr/share/cassandra/tools/cqlstress-counter-example.yaml
/usr/share/cassandra/tools/cqlstress-example.yaml
/usr/share/cassandra/tools/cqlstress-insanity-example.yaml
/usr/share/cassandra/tools/lib/stress.jar

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/cassandra.service
